### ISSUE TITLE
About dependency management

### ISSUE THREAD

**Issue by qouteall** [Gaider10/GravityChanger#20]
According to the ReadMe https://github.com/Gaider10/GravityChanger/blob/master/README.md , you recommend configuring dependency using the dev jar. The normal way that Fabric proposes is to publish the mod jar (not dev jar) into maven and use Maven for dependency. You can publish this mod to Modrinth https://modrinth.com/ then we can use the maven repo provided by Modrinth.

The dev jar dependency has these drawbacks:
* If the other mod's dev env uses a different version of yarn mapping, it may break. If that dev env use Mojang mapping, it cannot work
* If I don't put that jar into git, then other people forking my project can't compile. If I put that jar into git, the git file will swell if I upgrade the dependency (it's hard to fully delete things from a git repo)

**Comment by Gaider10** [comment]
Thanks for the info, I will try to do it that way
