### ISSUE TITLE
"3d vine" blocks only work when your standing on top of them

### ISSUE THREAD

**Issue by Ch1216** [Gaider10/GravityChanger#24]
by 3d vine blocks i mean, Cave vines/Glow berries, Twisting vines and Weeping vines, by standing on top of them I mean relatively on top (image for example)
(https://user-images.githubusercontent.com/68875386/146688871-4142ee7e-5483-4342-b732-fa5f5be21089.png)
 If you try to use them from beneath they don't work

**Comment by Gaider10** [comment]
That is how climbing works in minecraft, only the block your feet position is inside is checked, you can see the same behaviour in vanilla if you try to climb a ladder that is on your eye level, you won't be able to unless you jump.
