### ISSUE TITLE
Optifine causes camera issues

### ISSUE THREAD

**Issue by XDCam15** [Gaider10/GravityChanger#26]
First off, it's about time someone made a rotational gravity mod since 1.12!!!

The mod works great when I tried it out on 1.18.1. Then I decided to install optifine for 1.18.1 and things started to go whacky. The gravity still worked as intended, but the camera is no longer orientated correctly to the gravity direction. Its orientation stays as if my gravity is normal (down), but the camera does some freaky stuff when I look around, and it's way more apparent when I switch to 3rd person.

Is this mod not compatible with optifine? Hopefully this is just a bug with this version and I don't know if this bug exists in the 1.17 version or not. Haven't tried it yet.

Also, since I'm speaking here, I got a couple of suggestions:
-Is it possible to extend this mod's behavior to items, or more importantly all mobs? For example, using commands, all entities (@e) within certain coordinates or a certain radius will have their gravity direction changed to whatever is specified.
-And can you make a smooth camera transition switching between gravity directions like in the Starminer or Up and Down and All Around mods? The sudden camera switch is kinda nausea-inducing for me at least.

Other than this issue, and my suggestions, I'm loving this mod so far. Keep up the great work!

**Comment by Gaider10** [comment]
I'm not going to try make it compatible with optifine, so if it doesn't work it will probably stay that way
It would probably be possible to make it work for entities but i'm not going to as i think that would be too much work
Smooth camera transition was suggested before and i will probably add it if i ever find interest in making this mod again, so it could be soon or could be never
